### ISSUE TITLE
Great tool but before or after MQTT config ??

### ISSUE THREAD

**Issue by vincegre** [Psychokiller1888/satConnect#2]
Hi

I just setup some snips systems that I'm going to use in client/server mode so your tool looked to have worked fine but I'm concerned about something !
I runned your script on my SNIPS systems (server and satellites) just out of box (all snips system installed and audio config done).
Now I'm going to configure server to connect through MQTT to my home Assistant system. Is it going to break what script has done ? or should I run it again after havig setup server to connect to HA ?

Thanks for that great tool ;)

Vincèn

**Comment by Psychokiller1888** [comment]
Hi
It shouldn't break anything, as the script just added the satellites, nothing else

**Comment by vincegre** [comment]
Thanks and confirmed by real use ;) it didn't break my MQTT settings in snips (to connect at external MQTT server instead of internal one ;)
