### ISSUE TITLE
Failure each time at end of process !!

### ISSUE THREAD

**Issue by vincegre** [Psychokiller1888/satConnect#3]
Hi

I recently used again your cool tool but now it generates an error both on server and satellite !

On satellite, I get that:
```
Sending core configuration...
Main device updated and restarted
Restarting local Snips
All done! This satellite is now connected and should respond.
Press enter
Unfortunately we were unable to update the main device, aborting
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "connect.py", line 237, in onMessage
    raise KeyboardInterrupt
KeyboardInterrupt


Shutting down Snips SatConnect
```
And on server that:

```
pi@SNIPS-serveur:~/satConnect $ sudo python server.py 
Starting up Snips SatConnect Server
Server ip: 192.168.1.30
Backup already available
Configurations loaded
Checking name availability for satellite "cuisine"
Satellite name "cuisine@mqtt" is already declared
Adding satellite
Restarting local Snips
All done!
Updating and restarting Snips after adding satellite failed

Shutting down Snips SatConnect Server

```

The pi is up to date (both sat and main unit) and snips too !

Vincèn

**Comment by Psychokiller1888** [comment]
Hey! Sorry for that!

The error says that cuisine already exists

You did get a message telling you it's already in use? That's not the whole connect.py log

**Comment by vincegre** [comment]
```
The error says that cuisine already exists

You did get a message telling you it's already in use?
```
Yep I got a message about it and asking if I wanted to cancel or overwrite so I confirmed I wanted to overwrite ;) Does it help for the bug ?

**Comment by Psychokiller1888** [comment]
Well, the only thing I can see is that maybe the file /etc/snips.toml doesn't exist or is not writable. I don't see the problem. You did start with sudo right?

**Comment by fwehrle** [comment]
Hi,
Thank you for this nice project.
Beginning with Snips, I have the same error, but only on satelite.
My satelite's snips.toml file : 

> [snips-tts]
> [snips-dialogue]
> [snips-asr]
> [snips-nlu]
> [snips-asr-google]
> [snips-analytics]
> [snips-hotword]
> [snips-audio-server]
> bind = "Cuisine@mqtt"
> [snips-common]
> mqtt = "192.168.1.29:1883"

And the server one : 

> [snips-tts]
> 
> [snips-dialogue]
> 
> [snips-asr]
> 
> [snips-nlu]
> 
> [snips-asr-google]
> 
> [snips-analytics]
> 
> [snips-hotword]
> audio = ["default@mqtt", "Cuisine@mqtt"]
> 
> [snips-audio-server]
> bind = "default@mqtt"
> 
> [snips-common]

Both files belong to current user, and commands were running with sudo.
snips-audio-server is running on satelite, but the sam devices command is telling "No devices discovered".. Any advice? Thank you

**Comment by Psychokiller1888** [comment]
This seems correct, they have been added correctly. You can't add it a second time

**Comment by Psychokiller1888** [comment]
Will investigate this evening and be back with a fix

**Comment by fwehrle** [comment]
Ok. Thank you. The second time, I just clic "Yes" to replace the device in conf file : 

> The satellite name you chose is already taken.
> Are you replacing an existing device? If not, continuing may result in collisions!
> I am replacing an old device (Y) / No, change the satellite name (N): Y

**Comment by Psychokiller1888** [comment]
And if you answer yes, you get the error?

**Comment by fwehrle** [comment]
Yes

**Comment by Psychokiller1888** [comment]
Ok, thank you for the info, I'll debug in about an hour, gotta finish at work first :)

**Comment by fwehrle** [comment]
Thank you. I'll test it this we if you want.

**Comment by Psychokiller1888** [comment]
Ok, just tested and retested everything, this doesn't fail anymore

**Comment by vincegre** [comment]
+1, just tested it again on my SNIPS system and it now works perfect, without errors and do the wob perfectly ;)
Thanks for it @Psychokiller1888 :D

**Comment by Psychokiller1888** [comment]
You're welcome!

**Comment by fwehrle** [comment]
Yes. It work great. 
But I spend a lot time before seeing that your script empty the snips config file on server.. Is it possible to just fill the existing file with mqtt binding instead of replace it by an empty file?

**Comment by Psychokiller1888** [comment]
You mean, you want to leave the commented parts in the toml file?

**Comment by fwehrle** [comment]
Hum.. you're right.. 
I did not pay attention to this and I thought my problems came from that.
Sorry.

**Comment by Psychokiller1888** [comment]
Because of the way pytoml works, I can't keep the commented configurations unfortunately. Will build my own. In the meantime, the defaults available configs have been uploaded to the repository
